### ISSUE TITLE
php7.3.4连接报错

### ISSUE THREAD

**Issue by TryA9ain** [Richard-Tang/x1DecoderPlus#2]
![image](https://user-images.githubusercontent.com/51145610/110225573-d8a0d780-7f21-11eb-9a06-a68146663657.png)
![image](https://user-images.githubusercontent.com/51145610/110225580-e2c2d600-7f21-11eb-8aaa-2cb0bd00bdfc.png)
![image](https://user-images.githubusercontent.com/51145610/110225584-f0785b80-7f21-11eb-9398-af3f11d9c88a.png)
![image](https://user-images.githubusercontent.com/51145610/110225588-fec67780-7f21-11eb-8d94-ea8ee85a289a.png)
![image](https://user-images.githubusercontent.com/51145610/110225593-0b4ad000-7f22-11eb-9cda-32267aebe895.png)

**Comment by Richard-Tang** [comment]
现在应该可以了，大佬试一下，之前改shell.php时候没注意改错了。

**Comment by TryA9ain** [comment]
> 现在应该可以了，大佬试一下，之前改shell.php时候没注意改错了。

ok，可以用了，感谢大佬

**Comment by Richard-Tang** [comment]
> > 现在应该可以了，大佬试一下，之前改shell.php时候没注意改错了。
> 
> ok，可以用了，感谢大佬

好的大哥
