### ISSUE TITLE
最新版蚁剑jsp连不上

### ISSUE THREAD

**Issue by TryA9ain** [Richard-Tang/x1DecoderPlus#3]
![image](https://user-images.githubusercontent.com/51145610/116800641-a08acf00-ab35-11eb-94f6-4b415cb85d21.png)
### 一、 按照readme更改完毕 `source\modules\settings\encoders.js` 文件
![image](https://user-images.githubusercontent.com/51145610/116800669-ce701380-ab35-11eb-9b51-7d032f67ec21.png)
![image](https://user-images.githubusercontent.com/51145610/116800672-d9c33f00-ab35-11eb-9336-db011843a0fc.png)
### 二、替换` source\core\jsp\template\`
![image](https://user-images.githubusercontent.com/51145610/116800701-2eff5080-ab36-11eb-9ff6-0dd9748210cc.png)
### 四、连不上，一直转圈
![image](https://user-images.githubusercontent.com/51145610/116800739-6bcb4780-ab36-11eb-9088-20b168a7c2b2.png)
![image](https://user-images.githubusercontent.com/51145610/116800747-7c7bbd80-ab36-11eb-8478-68dc20711763.png)

**Comment by Richard-Tang** [comment]
不点击测试连接，直接添加后去双击打开能正常使用吗？

**Comment by TryA9ain** [comment]
> 不点击测试连接，直接添加后去双击打开能正常使用吗？

加载不进去
![image](https://user-images.githubusercontent.com/51145610/116800921-cc0eb900-ab37-11eb-9223-6a735c894e3f.png)

**Comment by Richard-Tang** [comment]
> > 不点击测试连接，直接添加后去双击打开能正常使用吗？
> 
> 加载不进去
> ![image](https://user-images.githubusercontent.com/51145610/116800921-cc0eb900-ab37-11eb-9223-6a735c894e3f.png)

好的，之后我看下。

**Comment by Richard-Tang** [comment]
> > 不点击测试连接，直接添加后去双击打开能正常使用吗？
> 
> 加载不进去
> ![image](https://user-images.githubusercontent.com/51145610/116800921-cc0eb900-ab37-11eb-9223-6a735c894e3f.png)

可以了，已经更新到对应的分支上了。

**Comment by TryA9ain** [comment]
> > > 不点击测试连接，直接添加后去双击打开能正常使用吗？
> > 
> > 
> > 加载不进去
> > ![image](https://user-images.githubusercontent.com/51145610/116800921-cc0eb900-ab37-11eb-9223-6a735c894e3f.png)
> 
> 可以了，已经更新到对应的分支上了。

over
